[build]
  publish = "."
  command = "echo 'No build required'"

[[redirects]]
  from = "/thank-you"
  to = "/thank-you.html"
  status = 200

[[redirects]]
  from = "/thank-you/"
  to = "/thank-you.html"
  status = 200
